### ISSUE TITLE
Plugin in S3

### ISSUE THREAD

**Issue by phillro** [ohnosequences/sbt-s3-resolver#18]
How would one load both sbt-s3-resolver plugin and a plugin that is itself stored in s3?

**Comment by Tvaroh** [comment]
@laughedelic, I have a plugin in which I want to access `sbt-s3-resolver` functionality. I've added

```scala
resolvers += "Era7 maven releases" at "http://releases.era7.com.s3.amazonaws.com"
addSbtPlugin("ohnosequences" % "sbt-s3-resolver" % "0.14.0")
```

to `project/project/plugins.sbt` like you said above and I'm trying to reference the plugin (`import ohnosequences.sbt.SbtS3Resolver._`) in project's source code (in `src/main/scala`), but it can't find it.

What am I doing wrong?

**Comment by laughedelic** [comment]
Hi @Tvaroh. I think it's not related to this issue, if I understood your right.

To use sbt-s3-resolver from another plugin, you should add those lines to your plugin's `build.sbt`, not `project/...`. 
If you _always_ want to add sbt-s3-resolver to projects with your plugin, you use `addSbtPlugin ` (just as you wrote), but if you only want to use its functionality from your plugin, you can use it as a normal library dependency:

```
resolvers += "Era7 maven releases" at "http://releases.era7.com.s3.amazonaws.com"

libraryDependencies += "ohnosequences" % "sbt-s3-resolver" % "0.14.0"
```

**Comment by Tvaroh** [comment]
@laughedelic thanks for the help, it does work. :+1:

**Comment by laughedelic** [comment]
@Tvaroh, you're welcome 😉

**Comment by Tvaroh** [comment]
@laughedelic sorry for late response. It's just a plugin containing common sbt stuff for projects in my organization.
