### ISSUE TITLE
Missing or invalid dependency

### ISSUE THREAD

**Issue by sbuljat** [ohnosequences/sbt-s3-resolver#41]
If my published artifact has a dependency on MongoDB driver library then project which depends on my library cannot compile without explicit MongoDB library dependency in build.sbt. Shouldn't it retrieve as transitive dependency? Tried maven and ivy style...same

**Comment by laughedelic** [comment]
Hi @sbuljat.
Can you show the `build.sbt` files of the project that depends on MongoDB and the the other one that depends on it? Also the version of sbt used and the error message could be useful.

**Comment by sbuljat** [comment]
Hi @laughedelic 

Here's build.sbt from project 1:

    name := "project-id"

    organization  := "com.project"

    version := "1.0.4"

    publishTo := {
      val prefix = if (isSnapshot.value) "snapshots" else "releases"
      Some(s3resolver.value("Releases", s3("releases.project.com")) withMavenPatterns)
    }

    s3credentials := file(".s3credentials")

    libraryDependencies ++= Seq(
        "org.scalatest" %% "scalatest" % "2.2.4" 	% "test",
        "com.typesafe" % "config" % "1.3.0",
        "org.mongodb" %% "casbah" % "3.0.0"
    )

Here's build.sbt from project 2:

    name := "project-ner"

    organization  := "com.project"

    version := "1.0.1"

    scalaVersion := "2.11.7"

    s3credentials := file(".s3credentials")

    resolvers ++= Seq[Resolver](
       s3resolver.value("Releases", s3("releases.project.com")).withMavenPatterns
    )

    libraryDependencies ++= Seq(
       "org.scalatest" %% "scalatest" % "2.2.4" % "test",
       "com.typesafe" %   "config" % "1.3.0",
       "com.project" %%  "project-id" % "1.0.4"
    )

Error in project 2:

[error] missing or invalid dependency detected while loading class file 'Location.class'.
[error] Could not access term mongodb in package com,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'Location.class' was compiled against an incompatible version of com.
[error] missing or invalid dependency detected while loading class file 'Location.class'.
[error] Could not access term casbah in value com.mongodb,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'Location.class' was compiled against an incompatible version of com.mongodb.
[error] missing or invalid dependency detected while loading class file 'Title.class'.

**Comment by laughedelic** [comment]
Wow :open_mouth:  I see such error for the first time. After quick googling I think it's some internal [scala/sbt issue](https://issues.scala-lang.org/browse/SI-9431) (also [here](https://github.com/sbt/sbt/issues/1803)). But this [SO question](http://stackoverflow.com/questions/27942110/parboiled2-causes-missing-or-invalid-dependency-detected-while-loading-class-fi) suggests that probably you can add some other mongodb related dependency and it will help. Here, unfortunately, I cannot help you.

And a couple of things related to the sbt-s3-resolver plugin:
- at the moment it [doesn't support](https://github.com/ohnosequences/sbt-s3-resolver#features) resolving maven dependencies (we have https://github.com/ohnosequences/sbt-s3-resolver/issues/7, but no much progress there)
- although if the published maven artifacts are public, you still [can resolve them](https://github.com/ohnosequences/sbt-s3-resolver#public-maven-artifacts)

**Comment by Liorba** [comment]
> at the moment it doesn't support resolving maven dependencies (we have #7, but no much progress there)

any updates on this one?

**Comment by laughedelic** [comment]
@Liorba you mean #7? 

> At the moment we don't use this functionality ourselves, and we don't have time to implement it. So if anybody will make a pull-request, it will be good.

**Comment by Liorba** [comment]
@laughedelic  yes..
