### ISSUE TITLE
Does not work for S3 Buckets in Frankfurt

### ISSUE THREAD

**Issue by felixnext** [ohnosequences/sbt-s3-resolver#47]
I just ran into the problem that the plugin does not for S3 Buckets in the Frankfurt region. After some research it appears that the Frankfurt region only supports the V4 signature Algorithms [[1](http://stackoverflow.com/questions/28213328/get-bucket-gives-bad-request-for-s3-buckets-i-didnt-create-via-boto)]. The upload fails with a 400 BAD REQUEST.
WORKAROUND: recreated the buckets in ireland.

However it would be nice to have support for Frankfurt.

**Comment by laughedelic** [comment]
Hey @felixnext I released a new version: [v0.16.0](https://github.com/ohnosequences/sbt-s3-resolver/releases/tag/v0.16.0) release with some updates and the fixes. It should solve the problem. Reopen the issue if the problem remains.
