### ISSUE TITLE
Optionally set object ACL

### ISSUE THREAD

**Issue by hkupty** [ohnosequences/sbt-s3-resolver#54]
Hi!
Currently, sbt-s3-resolver sets the default ACL value as `PublicRead`. While that can easily be changed to `Private`, I'd still need to have a `s3:PutObjectAcl` permission when running.

What I'd like is to optionally set the ACL value (such as `Some(CannedAccessControlList.PublicRead)`) and, if `None`, don't supply an ACL value at all, using the bucket default instead.

I understand that this would also affect `ivy-s3-resolver`, but if you agree, I can come up with PRs for both projects.

Cheers,
Henry Kupty

**Comment by laughedelic** [comment]
Hey @hkupty! Sounds like a good idea 👍

**Comment by laughedelic** [comment]
It's my pleasure 😊 Thanks for contributing!
